package lk.ijse.timbershop.service;

public enum ServiceType {
    ADDSAMPLE,CUSTOMERORDERPLACE,CUSTOMERORDER,CUSTOMER,EMPLOYEE,ITEM,LOGINFORM,MONTHLYINCOME,ORDERFORM,REQFURNITURE,SUPPLIERORDERPLACE,SUPPLIERORDER,SUPPLIER


}
